import { createRouter } from "@tanstack/react-router";
// routeTree.gen is auto-generated by @tanstack/router-plugin on first `npm run dev`
import { routeTree } from "./routeTree.gen";

export const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
